version: '3'
services:
  server:
    build: backend/
    ports: 
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_RS=qm_rs
    volumes:
      - ./backend/config.json:/server/config.json
  db:
    container_name: qm_mongo
    ports:
      - 27017:27017
    build: database/
    volumes:
      - data:/data/db
    entrypoint: ["mongod", "--config", "/etc/mongo/mongo.conf", "--replSet", "qm_rs", "--bind_ip", "localhost,qm_mongo"]

volumes:
  data: